[project]
name = "throwpillow"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "anthropic>=0.49.0",
    "dotenv>=0.9.9",
]
classifiers = ["Private :: Do Not Upload"]

[tool.pyright]
venvPath = "."
venv = ".venv"
